// Copyright 2026 Google LLC
// SPDX-License-Identifier: Apache-2.0

import AppKit
import Carbon.HIToolbox
import Foundation
import Sauce

/// Pasteboard insertion with conditional restoration and balanced synthetic keys.
@MainActor
public final class PasteInserter {
    public static let restoreDelay: TimeInterval = 1.0
    private static let sessionMarker = NSPasteboard.PasteboardType("com.ammaar.jot.transient")
    private static let transientType = NSPasteboard.PasteboardType("org.nspasteboard.TransientType")
    private static let autoGeneratedType = NSPasteboard.PasteboardType("org.nspasteboard.AutoGeneratedType")
    private static let eventQueue = DispatchQueue(label: "com.ammaar.jot.paste.events", qos: .userInteractive)
    private typealias Snapshot = [[NSPasteboard.PasteboardType: Data]]

    private struct Restoration {
        let id: UUID
        let snapshot: Snapshot
        let changeCount: Int
    }
    private let pasteboard: NSPasteboard
    private let delay: TimeInterval
    private let postPaste: () async -> Bool
    private var pending: Restoration?
    private var restoreTask: Task<Void, Never>?

    public convenience init() {
        self.init(pasteboard: .general, restoreDelay: Self.restoreDelay,
                  postPaste: { await PasteInserter.postCmdV() })
    }

    /// Test seam: isolated pasteboard and a poster that never injects real input.
    init(pasteboard: NSPasteboard, restoreDelay: TimeInterval,
         postPaste: @escaping () async -> Bool) {
        self.pasteboard = pasteboard
        self.delay = restoreDelay
        self.postPaste = postPaste
    }

    /// True means the events were posted, not that another app acknowledged them.
    /// History remains the durable copy. Restoration runs independently afterward.
    public func paste(_ text: String) async -> Bool {
        guard !Task.isCancelled else { return false }
        // Rapid dictations share the ORIGINAL clipboard snapshot. Filtering our
        // previous transcript out of a new snapshot instead produced an empty
        // snapshot, then erased the user's original clipboard at restore time.
        let snapshot: Snapshot
        if let pending, ownsClipboard(pending) {
            snapshot = pending.snapshot
        } else {
            snapshot = Self.snapshot(pasteboard)
        }
        restoreTask?.cancel()
        restoreTask = nil
        pending = nil

        let id = UUID()
        pasteboard.clearContents()
        let item = NSPasteboardItem()
        item.setString(text, forType: .string)
        item.setString(id.uuidString, forType: Self.sessionMarker)
        item.setString("", forType: Self.transientType)
        item.setString("", forType: Self.autoGeneratedType)
        guard pasteboard.writeObjects([item]) else {
            Self.restore(snapshot, to: pasteboard)
            return false
        }
        pending = Restoration(id: id, snapshot: snapshot, changeCount: pasteboard.changeCount)
        let posted = await postPaste()
        // A newer paste or copyOnly may have run while posting was suspended.
        guard pending?.id == id else { return posted }
        guard posted else {
            pending = nil // Leave this transcript available for manual paste.
            return false
        }

        let delay = self.delay
        restoreTask = Task { @MainActor [weak self] in
            do {
                try await Task.sleep(nanoseconds: UInt64(max(0, delay) * 1_000_000_000))
            } catch { return }
            guard let self, let pending = self.pending, pending.id == id else { return }
            if self.ownsClipboard(pending) {
                Self.restore(pending.snapshot, to: self.pasteboard)
            }
            self.pending = nil
            self.restoreTask = nil
        }
        return true
    }

    /// Permanent clipboard fallback. It also supersedes any earlier restore.
    public func copyOnly(_ text: String) {
        restoreTask?.cancel()
        restoreTask = nil
        pending = nil
        pasteboard.clearContents()
        let item = NSPasteboardItem()
        item.setString(text, forType: .string)
        item.setString("", forType: Self.transientType)
        pasteboard.writeObjects([item])
    }

    public static func warmKeyboardLayout() { _ = Sauce.shared }

    private static func postCmdV() async -> Bool {
        guard !Task.isCancelled,
              let source = CGEventSource(stateID: .privateState) else { return false }
        // Synthetic paste must never suppress the user's mouse or keyboard.
        source.localEventsSuppressionInterval = 0
        let permitted: CGEventFilterMask = [
            .permitLocalMouseEvents, .permitLocalKeyboardEvents, .permitSystemDefinedEvents
        ]
        source.setLocalEventsFilterDuringSuppressionState(permitted, state: .eventSuppressionStateSuppressionInterval)
        source.setLocalEventsFilterDuringSuppressionState(permitted, state: .eventSuppressionStateRemoteMouseDrag)
        let keyCode = CGKeyCode(Sauce.shared.keyCode(for: .v))
        guard let down = CGEvent(keyboardEventSource: source, virtualKey: keyCode, keyDown: true),
              let up = CGEvent(keyboardEventSource: source, virtualKey: keyCode, keyDown: false) else {
            return false
        }
        for event in [down, up] {
            event.flags = .maskCommand
            event.setIntegerValueField(.eventSourceUserData, value: SyntheticEventTag.magic)
        }
        return await withCheckedContinuation { continuation in
            eventQueue.async {
                // No actor hop between down/up: a busy main actor or cancelled
                // dictation cannot strand a pressed synthetic key. Serialize all
                // pairs and always post the release before resuming the caller.
                withExtendedLifetime(source) {
                    down.post(tap: .cghidEventTap)
                    defer { up.post(tap: .cghidEventTap) }
                    Thread.sleep(forTimeInterval: 0.01)
                }
                continuation.resume(returning: true)
            }
        }
    }

    private func ownsClipboard(_ restoration: Restoration) -> Bool {
        pasteboard.changeCount == restoration.changeCount
            && pasteboard.pasteboardItems?.first?.string(forType: Self.sessionMarker) == restoration.id.uuidString
    }

    private static func snapshot(_ pasteboard: NSPasteboard) -> Snapshot {
        (pasteboard.pasteboardItems ?? []).map { item in
            var entry: [NSPasteboard.PasteboardType: Data] = [:]
            for type in item.types {
                if let data = item.data(forType: type) { entry[type] = data }
            }
            return entry
        }
    }

    private static func restore(_ snapshot: Snapshot, to pasteboard: NSPasteboard) {
        pasteboard.clearContents()
        guard !snapshot.isEmpty else { return }
        pasteboard.writeObjects(snapshot.map { entry in
            let item = NSPasteboardItem()
            for (type, data) in entry { item.setData(data, forType: type) }
            return item
        })
    }
}
